trigger:
- Azure-main

pool:
  vmImage: ubuntu-latest

variables:
- group: CICD-Demo-var-group  # Link the variable group

steps:
# Step1: Checkout Code from GitHub
- checkout: self
  displayName: "Checkout GitHub repository"

#Step2:   Login to Docker Hub
- script: |
    set -e  # Stop script if any command fails
    echo "Logging in to Docker Hub..."
    echo $(DOCKER_PASSWORD) | docker login -u arasu35 --password-stdin
    docker info  # Verify login success
  displayName: "Login to Docker Hub"

#Step3:   Build Docker Image
- script: |
    set -e
    echo "Building the Docker image..."
    docker build -t arasu35/gatus:latest -f ./Dockerfile .
    docker images
  displayName: "Build Docker Image"

#Step4:   Push Image to Docker Hub
- script: |
    set -e
    echo "Tagging and pushing to Docker Hub..."
    docker push arasu35/gatus:latest
    sleep 7
  displayName: "Push Docker Image to Docker Hub"

#  Pull Docker Image on Azure VM
- task: AzureCLI@2
  displayName: "Pull Docker Image"
  inputs:
    azureSubscription: "CICD-Demo-Service-Connection"
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az vm run-command invoke \
        --resource-group CICD-demo-vm_group \
        --name CICD-demo-vm \
        --command-id RunShellScript \
        --scripts '
          echo "$(DOCKER_PASSWORD)" | docker login -u arasu35 --password-stdin;
          docker pull arasu35/gatus-azure:latest;
          sleep 10  
        '

#  Run Trivy Scan on Azure VM
- task: AzureCLI@2
  displayName: "Run Trivy Scan & Generate Report"
  inputs:
    azureSubscription: "CICD-Demo-Service-Connection"
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az vm run-command invoke \
        --resource-group CICD-demo-vm_group \
        --name CICD-demo-vm \
        --command-id RunShellScript \
        --scripts '

          # Run Trivy scan and store the HTML report in the Nginx HTML directory
          docker run --rm -v /home/azureuser/nginx/html:/output aquasec/trivy image --format template --template "@contrib/html.tpl" -o /output/trivy-report.html arasu35/gatus-azure:latest

          # Restart Nginx to reflect the new report
          docker restart nginx-reverse-proxy;
        '

#  Run Trivy Scan on Azure VM
- task: AzureCLI@2
  displayName: "Run Trivy Scan & Generate Report"
  inputs:
    azureSubscription: "CICD-Demo-Service-Connection"
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az vm run-command invoke \
        --resource-group CICD-demo-vm_group \
        --name CICD-demo-vm \
        --command-id RunShellScript \
        --scripts '
          docker stop gatus || true;
          docker rm gatus || true;
          docker run -d --name gatus -p 8081:8080 arasu35/gatus:latest;
        '

